drop table if exists equipment CASCADE;

create table equipment (id bigint generated by default as identity, date_of_purchase varchar(255) not null, model_name varchar(255) not null, unique_id_serial varchar(255) not null, primary key (id));

    alter table equipment add constraint UK_lspis9kyeag1gu7bun6wxybol unique (unique_id_serial);


drop table if exists equipment_type CASCADE;

create table equipment_type (id bigint generated by default as identity, name varchar(255) not null, primary key (id));

    alter table equipment_type add constraint UK_ly5pm93u4ps4l4936g1neschk unique (name);


drop table if exists organization CASCADE;

create table organization (id bigint generated by default as identity, location varchar(255) not null, name varchar(255) not null, primary key (id));

    alter table organization add constraint UK_2d01v70dyja5siieksttsxscp unique (location);
    alter table organization add constraint UK_8j5y8ipk73yx2joy9yr653c9t unique (name);


drop table if exists employee CASCADE;

create table employee (id bigint generated by default as identity, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), organization_id bigint, primary key (id));

    alter table employee add constraint FK2rna2w2imtuuk9f2et8yllawk foreign key (organization_id) references organization;