drop table if exists employee CASCADE;

// 2022-05-10
create table employee (id bigint generated by default as identity, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, phone_number varchar(255) not null, organization_id bigint, primary key (id));

    alter table employee add constraint UK_fopic1oh5oln2khj8eat6ino0 unique (email);
    alter table employee add constraint UK_ip7jcskqgx9yocqq9glr5b8vo unique (first_name);
    alter table employee add constraint UK_k19fiu1vgr79fo3urdkqqplw5 unique (last_name);
    alter table employee add constraint UK_if2qx9bhvigig71puh5sow65g unique (phone_number);
    alter table employee add constraint FK2rna2w2imtuuk9f2et8yllawk foreign key (organization_id) references organization;

// f2022-05-10
//create table employee (id bigint generated by default as identity, firstname varchar(255) not null, lastname varchar(255) not null, organization_id bigint, primary key (id));

//alter table employee add constraint UK_odeif7ievx2asgt77vtqtsbta unique (firstname);
//alter table employee add constraint UK_gph4f6140tr3riucjcy5jkx7b unique (lastname);


--create table employee (id bigint generated by default as identity, firstname varchar(255) not null, org_id integer not null, organization_id bigint, primary key (id));

--alter table employee add constraint UK_odeif7ievx2asgt77vtqtsbta unique (firstname);
--alter table employee add constraint UK_j3t6cbvfqphukt6qc7sxcgm39 unique (org_id);
//alter table employee add constraint FK2rna2w2imtuuk9f2et8yllawk foreign key (organization_id) references organization;

/*
create table employee (id bigint generated by default as identity, firstname varchar(255) not null, organization_id integer not null, primary key (id));
alter table employee add constraint UK_odeif7ievx2asgt77vtqtsbta unique (firstname);
alter table employee add constraint UK_sfap0psgqho076hl6mwkaf9m9 unique (organization_id);
*/