drop table if exists equipment CASCADE;

create table equipment (id bigint generated by default as identity, date_of_purchase varchar(255) not null, model_name varchar(255) not null, unique_id_serial varchar(255) not null, primary key (id));

    alter table equipment add constraint UK_lspis9kyeag1gu7bun6wxybol unique (unique_id_serial)